<!DOCTYPE html>
<html>

<head>

<meta charset="UTF-8">

<title>@yield('title')</title>

<style>

*{
    margin:0;
    padding:0;
    box-sizing:border-box;
    font-family: DejaVu Sans, sans-serif;
}

body{
    font-size:12px;
    color:#222;
}

.header{
    border-bottom:3px solid #2563eb;
    padding-bottom:12px;
    margin-bottom:20px;
}

.logo{
    float:left;
    width:70px;
}

.logo img{
    width:65px;
}

.university{
    margin-left:85px;
}

.university h1{
    font-size:22px;
    color:#1e40af;
}

.university h3{
    color:#555;
    font-size:14px;
    margin-top:4px;
}

.clear{
    clear:both;
}

.report-title{
    text-align:center;
    font-size:20px;
    font-weight:bold;
    margin:20px 0;
    color:#111827;
}

.info{
    margin-bottom:18px;
}

.info table{
    width:100%;
}

.info td{
    padding:4px;
}

table.report{
    width:100%;
    border-collapse:collapse;
    margin-top:15px;
}

table.report th{
    background:#2563eb;
    color:white;
    padding:10px;
    border:1px solid #ddd;
    font-size:12px;
}

table.report td{
    border:1px solid #ddd;
    padding:8px;
}

table.report tr:nth-child(even){
    background:#f8fafc;
}

.footer{
    position:fixed;
    bottom:-20px;
    left:0;
    right:0;
    text-align:center;
    font-size:11px;
    color:#777;
    border-top:1px solid #ddd;
    padding-top:6px;
}

.page-number:after{
    content: counter(page);
}

.signature{
    margin-top:80px;
}

.sign-box{
    width:220px;
    text-align:center;
    float:right;
}

.sign-line{
    border-top:1px solid #000;
    margin-bottom:5px;
}

</style>

</head>

<body>

<div class="header">




    <div class="university">

        <h1>Exam Seat Management System</h1>

        <h3>Metropolitan University</h3>

        <p>Sylhet, Bangladesh</p>

    </div>

    <div class="clear"></div>

</div>

<div class="report-title">

@yield('report_title')

</div>

<div class="info">

<table>

<tr>

<td>

<strong>Generated At :</strong>

{{ now()->format('d M Y') }}

</td>

<td align="right">

<strong>Generated By :</strong>

{{ auth()->user()->name }}

</td>

</tr>

</table>

</div>

@yield('content')

<div class="signature">

<div class="sign-box">

<div class="sign-line"></div>

Controller of Examination

</div>

</div>

<div class="footer">

Exam Seat Management System

|

Generated on {{ now()->format('d M Y') }}

|

Page <span class="page-number"></span>

</div>

</body>

</html>